defmodule ChanneledBeats.Repo.Migrations.AddAlbums do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:users, [:username], name: "users_unique_username_index")

    alter table(:beats) do
      add :album_id, :uuid, null: false
    end

    create table(:albums, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    alter table(:beats) do
      modify :album_id,
             references(:albums,
               column: :id,
               name: "beats_album_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:albums) do
      add :name, :text, null: false
      add :extension, :text, null: false
    end
  end

  def down do
    alter table(:albums) do
      remove :extension
      remove :name
    end

    drop constraint(:beats, "beats_album_id_fkey")

    alter table(:beats) do
      modify :album_id, :uuid
    end

    drop table(:albums)

    alter table(:beats) do
      remove :album_id
    end

    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")
  end
end